language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - 'node_modules'
before_install:
  - npm install -g codecov yarn
install:
  - yarn
script:
  - yarn lint
  - yarn test:codecov
after_success:
  - codecov

